### ISSUE TITLE
Maksekeskus return_url is not updated when wordpress home url is changed

### ISSUE THREAD

**Issue by martinl** [KonektOU/estonian-banklinks-for-woocommerce#17]
Maksekeskus gateway return_url value is stored in Wordpress options table (option_value woocommerce_maksekeskus_redirect_settings) on first plugin install and is not updated when home url is changed in Wordpress settings (eg when switching site from http to https after plugin install). This means that redirects back from Maksekeskus will fail.

Setting return urls in Maksekeskus user portal as workaround does work because the local return_url overrides portal settings. Uninstalling and reinstalling the plugin does not work either since plugin settings are retained after uninstall. Afaik, only way to update the return_url value is directly in the database.

For possible solutions, please check and update return_url value with current woocommerce api url when saving Maksekeskus gateway settings and/or add option to remove the plugin settings when plugin is uninstalled

**Comment by RistoNiinemets** [comment]
Thanks for the report. I can see why and when this could happen.

However, how do you change the site URL? Do you use a plugin for that or something else. The reason I ask is because if the site URL is migrated to another URL properly, all old URLs in database should be replaced with new ones, whether they are in serialized data or not.

**Comment by martinl** [comment]
I changed site and home url (http:// > https://) in wordpress admin > options > general

**Comment by RistoNiinemets** [comment]
Okay. Well, this is surely not a recommended way to do it. There are a lot of plugins which do the work for you. For example, WP Migrate DB is a really good one. 

It will ensure all your links will be correct, otherwise there could be redirects from http to https and Google does not like it very much.

**Comment by martinl** [comment]
Thanks, I think the issue can be closed
